apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tofood-role-binding
  namespace: tofood
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tofood
roleRef:
  kind: Role
  name: tofood-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tofood-role
  namespace: tofood
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
