name: Destroy Infra

on:
  workflow_dispatch: # Executado manualmente

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      TF_VERSION: 1.0.0
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.0.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # Step to terminate EC2 instances
      - name: Terminate EC2 Instances
        run: |
          INSTANCE_IDS=$(aws ec2 describe-instances --query "Reservations[*].Instances[?State.Name=='running'].InstanceId" --output text)
          if [ -z "$INSTANCE_IDS" ]; then
            echo "Nenhuma instância EC2 em execução encontrada."
          else
            echo "Encerrando instâncias EC2: $INSTANCE_IDS"
            aws ec2 terminate-instances --instance-ids $INSTANCE_IDS
            aws ec2 wait instance-terminated --instance-ids $INSTANCE_IDS
            echo "Instâncias EC2 encerradas com sucesso."
          fi

      # Step to delete load balancers
      - name: Delete Load Balancers
        run: |
          LB_ARN_LIST=$(aws elbv2 describe-load-balancers --query "LoadBalancers[*].LoadBalancerArn" --output text)
          if [ -z "$LB_ARN_LIST" ]; then
            echo "Nenhum Load Balancer encontrado."
          else
            for LB_ARN in $LB_ARN_LIST; do
              echo "Excluindo Load Balancer: $LB_ARN"
              aws elbv2 delete-load-balancer --load-balancer-arn $LB_ARN
            done
          fi

      # Step to delete security groups
      - name: Delete Security Groups
        run: |
          SG_IDS=$(aws ec2 describe-security-groups --query "SecurityGroups[?GroupName!='default'].GroupId" --output text)
          if [ -z "$SG_IDS" ]; then
            echo "Nenhum Security Group encontrado."
          else
            for SG_ID in $SG_IDS; do
              echo "Excluindo Security Group: $SG_ID"
              aws ec2 delete-security-group --group-id $SG_ID || echo "Erro ao excluir $SG_ID. Verifique dependências."
            done
          fi

      # Step to delete subnets and VPCs
      - name: Destroy VPCs and Associated Resources
        run: |
          VPC_IDS=$(aws ec2 describe-vpcs --query "Vpcs[*].VpcId" --output text)
          for VPC_ID in $VPC_IDS; do
            echo "Excluindo recursos associados à VPC: $VPC_ID"

            # Remove subnets
            SUBNET_IDS=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --query "Subnets[*].SubnetId" --output text)
            for SUBNET_ID in $SUBNET_IDS; do
              echo "Excluindo Subnet: $SUBNET_ID"
              aws ec2 delete-subnet --subnet-id $SUBNET_ID || echo "Erro ao excluir Subnet: $SUBNET_ID"
            done

            # Remove internet gateways
            IGW_IDS=$(aws ec2 describe-internet-gateways --filters "Name=attachment.vpc-id,Values=$VPC_ID" --query "InternetGateways[*].InternetGatewayId" --output text)
            for IGW_ID in $IGW_IDS; do
              echo "Desanexando e excluindo Internet Gateway: $IGW_ID"
              aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID
              aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID
            done

            # Exclui a VPC
            echo "Excluindo VPC: $VPC_ID"
            aws ec2 delete-vpc --vpc-id $VPC_ID || echo "Erro ao excluir a VPC: $VPC_ID"
          done

      - name: Terraform Init
        run: cd terraform/destroy-only && terraform init

      - name: Terraform Plan Destroy
        run: cd terraform/destroy-only && terraform plan -destroy -out=tfplan

      - name: Terraform Apply Destroy
        run: cd terraform/destroy-only && terraform apply -auto-approve tfplan
