name: Validate Kubernetes Cluster

on:
  workflow_dispatch: # Permite que o pipeline seja executado manualmente

jobs:
  validate-kubernetes:
    name: Validate Kubernetes Setup
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
      KUBERNETES_CLUSTER_NAME: "tofood-eks-cluster" # Nome do cluster

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name $KUBERNETES_CLUSTER_NAME --region ${{ vars.AWS_REGION }}

      - name: Get Kubernetes Cluster Nodes
        run: kubectl get nodes

      - name: Validate Namespace Creation
        run: |
          kubectl apply --dry-run=client -f kubernetes/namespaces.yaml
          kubectl apply --dry-run=client -f kubernetes/rbac.yaml

      - name: Lint Kubernetes Manifests (Optional)
        run: |
          kubeval kubernetes/namespaces.yaml
          kubeval kubernetes/rbac.yaml
